### ISSUE TITLE
Add option to not add any furigana

### ISSUE THREAD

**Issue by KarolS** [max-kamps/jpd-breader#97]
Lack of that option is really annoying when using ttsu reader.

### Steps to reproduce:

* add `.jpdb-furi { display: none; }` to Breader's CSS
* open ttsu reader
* optional: in ttsu settings, enable "Auto Bookmark"
* optional: in ttsu settings, enable "Avoid Page Break"
* in ttsu reader, open a book with kanji and no furigana
* 
### What should happen:

* After parsing, the text changes colour and that's it.

### What actually happens:

* The entire page does a relayout, causing:
    * ghosting on e-ink devices
    * if Auto Bookmark is on: invalid placement of automatic ttsu bookmarks
    * annoyance
    * (the effect is more noticeable if "Avoid Page Break" is on)

The reason for this behaviour is this piece of ttsu's CSS:

```css
.book-content--writing-vertical-rl.svelte-16m55p4 .book-content-container>*:not(.ttu-book-html-wrapper)>*:has(ruby):has(rt),
.book-content--writing-vertical-rl.svelte-16m55p4 .book-content-container>div.ttu-book-html-wrapper>div.ttu-book-body-wrapper>*>*:has(ruby):has(rt) {
  padding-right:10px!important
}
```

which adds padding for all paragraphs containing a `ruby` tag with furigana, even if furigana is invisible and zero-size. Since the text does not contain ruby tags before parsing and does contain them after parsing, the padding changes, shoving everything to the left, often to the next page.

### Very Ugly Workaround:

Add to Breader's CSS:

```css
ruby.jpdb-word { display: inline; }
div.ttu-book-html-wrapper>div.ttu-book-body-wrapper>*>p {
  padding-right:10px!important
}
```

It doesn't work 100% correctly in all browsers though.
